/**
 * Image and icon sources pulled from the Figma file, all localized under public/assets.
 */
export const assets = {
  logo: {
    cube1: "/assets/logo/cube1.svg",
    cube2: "/assets/logo/cube2.svg",
  },
  icons: {
    arrowNarrowRight: "/assets/icons/arrow-narrow-right.svg",
    download: "/assets/icons/download.svg",
    downloadHover: "/assets/icons/download-hover.svg",
    downloadBgHover: "/assets/icons/download-bg-hover.svg",
    money: "/assets/icons/money.svg",
    confidence: "/assets/icons/confidence.svg",
    trust: "/assets/icons/trust.svg",
    medium: "/assets/icons/medium.svg",
    mediumWordmark: "/assets/icons/medium-wordmark.png",
    chevronRight: "/assets/icons/chevron-right.svg",
    chevronRightWhite: "/assets/icons/chevron-right-white.svg",
    linkOutBlack: "/assets/icons/link-out-black.svg",
    linkOutOrange: "/assets/icons/link-out-orange.svg",
    phoneBadge: "/assets/icons/phone-badge.svg",
    downloadBadge: "/assets/icons/download-badge.svg",
    linkedinBadge: "/assets/icons/linkedin-badge.svg",
    gmailBadge: "/assets/icons/gmail-badge.svg",
  },
  photos: {
    profile: "/assets/photos/profile.svg",
    blogPreview: "/assets/photos/blog-preview.png",
  },
  brands: {
    valueResearchMark: "/assets/brands/value-research-mark.svg",
    valueResearchBadge: "/assets/brands/value-research-badge.svg",
    relaxo: "/assets/brands/relaxo.svg",
    amazon: "/assets/brands/amazon.svg",
    bajajAuto: "/assets/brands/bajaj-auto.svg",
  },
  about: {
    skillCards: {
      stakeholderBuyin: "/assets/about/skill-stakeholder-buyin.svg",
      realSignals: "/assets/about/skill-real-signals.svg",
      handoffSpecs: "/assets/about/skill-handoff-specs.svg",
      sessionRecording: "/assets/about/skill-session-recording.svg",
      edgeCases: "/assets/about/skill-edge-cases.svg",
      lowFiHighSignal: "/assets/about/skill-lowfi-highsignal.svg",
    },
    principleCards: {
      buildForChange: "/assets/about/principle-card-build-for-change.svg",
      designForPerson: "/assets/about/principle-card-design-for-person.svg",
      shipItRight: "/assets/about/principle-card-ship-it-right.svg",
      bridging: "/assets/about/principle-card-bridging.svg",
    },
    principleCardsHover: {
      buildForChange: "/assets/about/principle-card-build-for-change-hover.svg",
      designForPerson: "/assets/about/principle-card-design-for-person-hover.svg",
      shipItRight: "/assets/about/principle-card-ship-it-right-hover.svg",
      bridging: "/assets/about/principle-card-bridging-hover.svg",
    },
    outsideWork: {
      photo1: "/assets/about/outside-photo1.jpg",
      photo2: "/assets/about/outside-photo2.jpg",
      photo3: "/assets/about/outside-photo3.jpg",
      photo4: "/assets/about/outside-photo4.jpg",
      photo5: "/assets/about/outside-photo5.jpg",
      photo6: "/assets/about/outside-photo6.jpg",
      photo7: "/assets/about/outside-photo7.jpg",
      photo8: "/assets/about/outside-photo8.jpg",
      photo9: "/assets/about/outside-photo9.jpg",
      photo10: "/assets/about/outside-photo10.jpg",
    },
  },
  workCovers: {
    vrAdvisorApp: "/assets/work-covers/vr-advisor-app.svg",
    ledgerDesignSystem: "/assets/work-covers/ledger-design-system.svg",
    stockScreener: "/assets/work-covers/stock-screener-redesign.svg",
    zohoMarketing: "/assets/work-covers/zoho-marketing-experience.svg",
  },
  work: {
    vrAdvisorApp: {
      figmaIcon: "/assets/work/icon-figma.png",
      marqueeIcon: "/assets/work/vr-advisor-app/marquee-icon.svg",
      heroComposite: "/assets/work/vr-advisor-app/hero-composite.svg",
      cardResearch: "/assets/work/vr-advisor-app/card-research.svg",
      cardInvest: "/assets/work/vr-advisor-app/card-invest.svg",
      cardTrackPortfolio: "/assets/work/vr-advisor-app/card-track-portfolio.svg",
      cardManageSubscriptions: "/assets/work/vr-advisor-app/card-manage-subscriptions.svg",
      cardCompleteTransactions: "/assets/work/vr-advisor-app/card-complete-transactions.svg",
      cardAccountSettings: "/assets/work/vr-advisor-app/card-account-settings.svg",
      problem1: "/assets/work/vr-advisor-app/problem-1.svg",
      problem2: "/assets/work/vr-advisor-app/problem-2.svg",
      problem3: "/assets/work/vr-advisor-app/problem-3.svg",
      problem4: "/assets/work/vr-advisor-app/problem-4.svg",
      problemSS: "/assets/work/vr-advisor-app/problemSS.svg",
      smartphoneRockMockup: "/assets/work/vr-advisor-app/smartphone-rock-mockup.svg",
      orderConfirmationHands: "/assets/work/vr-advisor-app/order-confirmation-hands.svg",
      fundDetailAndScreenerPhones: "/assets/work/vr-advisor-app/fund-detail-and-screener-phones.svg",
      discoverPhone1: "/assets/work/vr-advisor-app/discover-phone-1.svg",
      discoverPhone2: "/assets/work/vr-advisor-app/discover-phone-2.svg",
      discoverPhone3: "/assets/work/vr-advisor-app/discover-phone-3.svg",
      discoverPhone4: "/assets/work/vr-advisor-app/discover-phone-4.svg",
      confidentDecisionsDashboard: "/assets/work/vr-advisor-app/confident-decisions-dashboard.svg",
      confidentDecisionsFundDetail: "/assets/work/vr-advisor-app/confident-decisions-fund-detail.svg",
      confidentDecisionsRiskGauge: "/assets/work/vr-advisor-app/confident-decisions-risk-gauge.svg",
      confidentDecisionsWhereInvests: "/assets/work/vr-advisor-app/confident-decisions-where-invests.svg",
      transactionPhone1: "/assets/work/vr-advisor-app/transaction-phone-1-sip-amount.svg",
      transactionPhone2: "/assets/work/vr-advisor-app/transaction-phone-2-bank-payment.svg",
      transactionPhone3: "/assets/work/vr-advisor-app/transaction-phone-3-otp.svg",
      transactionPhone4: "/assets/work/vr-advisor-app/transaction-phone-4-upi-wait.svg",
      transactionPhone5: "/assets/work/vr-advisor-app/transaction-phone-5-sip-registered.svg",
      informedPhone1: "/assets/work/vr-advisor-app/informed-phone-1-attention.svg",
      informedPhone2: "/assets/work/vr-advisor-app/informed-phone-2-performance.svg",
      informedPhone3: "/assets/work/vr-advisor-app/informed-phone-3-portfolio-summary.svg",
      accountPhone1: "/assets/work/vr-advisor-app/account-phone-1-investor-account.svg",
      accountPhone2: "/assets/work/vr-advisor-app/account-phone-2-autopay-mandates.svg",
      accountPhone3: "/assets/work/vr-advisor-app/account-phone-3-transaction-history.svg",
      accountPhone4: "/assets/work/vr-advisor-app/account-phone-4-fund-details.svg",
      iaDiagram: "/assets/work/vr-advisor-app/ia-diagram.svg",
      goalHomePhone1: "/assets/work/vr-advisor-app/goal-home-phone-1-import.svg",
      goalHomePhone2: "/assets/work/vr-advisor-app/goal-home-phone-2-portfolio.svg",
      goalHomePhone3: "/assets/work/vr-advisor-app/goal-home-phone-3-dark-mode.svg",
      detailPhone1: "/assets/work/vr-advisor-app/detail-phone-1-fund-info.svg",
      detailPhone2: "/assets/work/vr-advisor-app/detail-phone-2-returns-chart.svg",
      detailPhone3: "/assets/work/vr-advisor-app/detail-phone-3-nfo-period.svg",
      detailPhone4: "/assets/work/vr-advisor-app/detail-phone-4-sif-fund.svg",
      regulatedOtpVerification: "/assets/work/vr-advisor-app/regulated-otp-verification.svg",
      regulatedRiskProfile: "/assets/work/vr-advisor-app/regulated-risk-profile.svg",
      regulatedFundDetail: "/assets/work/vr-advisor-app/regulated-fund-detail.svg",
      closingIllustration: "/assets/work/vr-advisor-app/closing-illustration-put-money-to-work.svg",
      reviewScreen: "/assets/work/vr-advisor-app/review_screen.svg",
    },
    stockScreener: {
      heroCover: "/assets/work/stock-screener-hero-cover.svg",
      oldDesign: "/assets/work/stock-screener-old-design.svg",
      newDesign: "/assets/work/stock-screener-new-design.svg",
      mobilePhones: "/assets/work/stock-screener-mobile-phones.svg",
      columnsPanel: "/assets/work/stock-screener-columns-panel.svg",
      illustrations: "/assets/work/stock-screener-illustrations.svg",
      components: "/assets/work/stock-screener-components.svg",
      figmaIcon: "/assets/work/icon-figma.png",
    },
    ledgerDesignSystem: {
      ledgerBg: "/assets/work/ledger-design-system/ledger_bg.svg",
      tokensVariablesPanel: "/assets/work/ledger-design-system/tokens-variables-panel.svg",
      colorPalette1: "/assets/work/ledger-design-system/color-palette-1.svg",
      colorPalette2: "/assets/work/ledger-design-system/color-palette-2.svg",
      typographySpecimens: "/assets/work/ledger-design-system/typography-specimens.svg",
      iconWall: "/assets/work/ledger-design-system/icon-wall.svg",
      iconGridStyles: "/assets/work/ledger-design-system/icon-grid-styles.svg",
      voiceAuthoritative: "/assets/work/ledger-design-system/voice-authoritative.svg",
      voiceWarm: "/assets/work/ledger-design-system/voice-warm.svg",
      voiceClear: "/assets/work/ledger-design-system/voice-clear.svg",
      voiceObjective: "/assets/work/ledger-design-system/voice-objective.svg",
      illustrationsGallery: "/assets/work/ledger-design-system/illustrations-gallery.svg",
      spacingGridTokens: "/assets/work/ledger-design-system/spacing-grid-tokens.svg",
      dataVisualizationComponents: "/assets/work/ledger-design-system/data-visualization-components.svg",
      componentLibrary: "/assets/work/ledger-design-system/component-library.svg",
      inProductionMockup: "/assets/work/ledger-design-system/in-production-mockup.svg",
    },
    zohoMarketing: {
      heroMockup: "/assets/work/zoho-marketing-experience/hero-website-mockup.svg",
      marqueeIcon: "/assets/work/zoho-marketing-experience/marquee-divider-icon.svg",
      toolIconFigma: "/assets/work/zoho-marketing-experience/tool-icon-figma.png",
      toolIconClaude: "/assets/work/zoho-marketing-experience/tool-icon-claude.svg",
      oldDesignDeskMob: "/assets/work/zoho-marketing-experience/old-design-desk-mob.svg",
      auditIconGenericMessaging: "/assets/work/zoho-marketing-experience/audit-icon-generic-messaging.svg",
      auditIconDifficultToScan: "/assets/work/zoho-marketing-experience/audit-icon-difficult-to-scan.svg",
      auditIconLowConversion: "/assets/work/zoho-marketing-experience/audit-icon-low-conversion.svg",
      auditIconMissingDecisionSupport: "/assets/work/zoho-marketing-experience/audit-icon-missing-decision-support.svg",
      auditIconWeakDifferentiation: "/assets/work/zoho-marketing-experience/audit-icon-weak-differentiation.svg",
      auditIconInconsistentStructure: "/assets/work/zoho-marketing-experience/audit-icon-inconsistent-structure.svg",
      designStrategyPhoneMockup: "/assets/work/zoho-marketing-experience/design-strategy-phone-mockup.svg",
      keyDesignPoints: "/assets/work/zoho-marketing-experience/key-design-points.svg",
      finalSolutionDesktopMockup: "/assets/work/zoho-marketing-experience/final-solution-desktop-mockup.svg",
      finalMobileImages: "/assets/work/zoho-marketing-experience/final-mobile-images.svg",
      finalTakeawayBg: "/assets/work/zoho-marketing-experience/final-takeaway-bg.svg",
    },
  },
  microLab: {
    video1: "/assets/micro-lab/micro-lab-1.mp4",
    video2: "/assets/micro-lab/micro-lab-2.mp4",
    video3: "/assets/micro-lab/micro-lab-3.mp4",
    image1: "/assets/micro-lab/micro-lab-4.svg",
    image2: "/assets/micro-lab/micro-lab-5.svg",
    image3: "/assets/micro-lab/micro-lab-6.svg",
  },
  whatIf: {
    whatsappScheduling: "/assets/what-if/whatsapp-scheduling.svg",
  },
} as const;
